#!/usr/bin/env python3
"""Regenerate the small, deterministic research navigation files.

The generator reads directory README files for node titles/statuses and the
migration map for historical aliases. It deliberately does not inspect an LLM,
database, embedding service, or external application.
"""

from __future__ import annotations

import csv
import re
from io import StringIO
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
RESEARCH = ROOT / "research"
PROVENANCE = ROOT / "provenance"
MIGRATION_MAP = PROVENANCE / "MIGRATION_MAP.tsv"


def rel(path: Path) -> str:
    return path.relative_to(ROOT).as_posix()


def read_text(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="replace")


def title_and_status(path: Path) -> tuple[str, str]:
    readme = path / "README.md"
    if not readme.is_file():
        return path.name.replace("-", " ").title(), ""
    text = read_text(readme)
    title = ""
    for line in text.splitlines():
        match = re.match(r"^#\s+(.+?)\s*$", line)
        if match:
            title = match.group(1)
            break
    status = ""
    status_match = re.search(r"(?im)^\s*status\s*:\s*([^\n]+)", text)
    if status_match:
        status = status_match.group(1).strip().strip("`")
    if not status:
        lines = text.splitlines()
        for index, line in enumerate(lines):
            if not re.match(r"^\s*##\s+status\s*$", line, flags=re.IGNORECASE):
                continue
            for candidate in lines[index + 1 :]:
                candidate = candidate.strip()
                if not candidate:
                    continue
                status = candidate.lstrip("- ").strip().strip("`")
                break
            if status:
                break
    return title or path.name.replace("-", " ").title(), status


def file_title(path: Path) -> str:
    text = read_text(path)
    title_match = re.search(r"(?m)^#\s+(.+?)\s*$", text)
    if title_match:
        return title_match.group(1).strip()
    front_match = re.search(r"(?im)^title\s*:\s*(.+?)\s*$", text)
    if front_match:
        return front_match.group(1).strip().strip("'\"")
    return path.stem.replace("-", " ").replace("_", " ").title()


def active_paths() -> list[Path]:
    paths: list[Path] = []
    if not RESEARCH.is_dir():
        return paths
    for path in RESEARCH.rglob("*"):
        if not path.is_file():
            continue
        relative = path.relative_to(RESEARCH).parts
        if relative and relative[0] == "archive":
            continue
        if path.name == "README.md":
            continue
        paths.append(path)
    return sorted(paths, key=lambda item: rel(item).lower())


def has_files(path: Path) -> bool:
    return any(child.is_file() for child in path.rglob("*"))


def render_tree() -> str:
    lines = [
        "# Mathematical research tree",
        "",
        "Generated by `python tools/update-research-index.py`; archive contents are",
        "shown only at their boundary because their internal names are frozen provenance.",
        "",
    ]

    def visit(path: Path, prefix: str, is_last: bool) -> None:
        title, status = title_and_status(path)
        relative = rel(path) + "/"
        suffix = f" — {title}"
        if status:
            suffix += f" (status: {status})"
        branch = "└── " if is_last else "├── "
        lines.append(f"{prefix}{branch}`{relative}`{suffix}")

        if path == RESEARCH / "archive":
            return
        children = [
            child for child in path.iterdir() if child.is_dir() and has_files(child)
        ]
        children = [child for child in children if child.name != ".git"]
        children.sort(key=lambda child: child.name.lower())
        next_prefix = prefix + ("    " if is_last else "│   ")
        for index, child in enumerate(children):
            visit(child, next_prefix, index == len(children) - 1)

    if RESEARCH.is_dir():
        # The root node is printed without a branch glyph.
        title, status = title_and_status(RESEARCH)
        suffix = f" — {title}"
        if status:
            suffix += f" (status: {status})"
        lines.append(f"`research/`{suffix}")
        children = [
            child for child in RESEARCH.iterdir() if child.is_dir() and has_files(child)
        ]
        children.sort(key=lambda child: child.name.lower())
        for index, child in enumerate(children):
            visit(child, "", index == len(children) - 1)
    return "\n".join(lines) + "\n"


def read_migration_rows() -> list[dict[str, str]]:
    if not MIGRATION_MAP.is_file():
        return []
    with MIGRATION_MAP.open("r", encoding="utf-8", newline="") as handle:
        return list(csv.DictReader(handle, delimiter="\t"))


def render_index() -> str:
    lines = [
        "# Canonical research index",
        "",
        "Generated by `python tools/update-research-index.py`. Historical source",
        "paths are listed in `provenance/ALIASES.tsv`; this list focuses on active",
        "mathematical files outside the frozen archive mirror.",
        "",
        "| Kind | Title | Path |",
        "| --- | --- | --- |",
    ]
    kinds: dict[str, str] = {}
    for row in read_migration_rows():
        canonical = row.get("canonical_path", "")
        if canonical and canonical not in kinds:
            kinds[canonical] = row.get("artifact_kind", "") or "record"
    for path in active_paths():
        path_text = rel(path)
        kind = kinds.get(path_text, "record")
        title = file_title(path).replace("|", "\\|")
        lines.append(f"| {kind} | {title} | [`{path_text}`]({path_text}) |")
    return "\n".join(lines) + "\n"


def render_aliases() -> str:
    header = ["alias", "canonical_path", "source_repository", "disposition", "relationship", "notes"]
    records: dict[tuple[str, str], list[str]] = {}
    for row in read_migration_rows():
        canonical = row.get("canonical_path", "")
        if not canonical:
            continue
        source_repo = row.get("source_repository", "")
        disposition = row.get("disposition", "")
        relationship = row.get("relationship", "")
        notes = row.get("notes", "")
        candidates = []
        source_path = row.get("source_path", "")
        if source_path:
            candidates.append(f"{source_repo}:{source_path}")
            candidates.append(source_path)
        old_destination = row.get("destination_existing_path", "")
        if old_destination:
            candidates.append(f"destination:{old_destination}")
        candidates.extend(
            item.strip() for item in row.get("aliases", "").split(";") if item.strip()
        )
        for alias in candidates:
            key = (alias, canonical)
            records.setdefault(key, [source_repo, disposition, relationship, notes])

    stream = StringIO()
    output = csv.writer(stream, delimiter="\t", lineterminator="\n")
    output.writerow(header)
    for (alias, canonical), metadata in sorted(records.items(), key=lambda item: item[0]):
        output.writerow([alias, canonical, *metadata])
    return stream.getvalue()


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")


def main() -> None:
    write(ROOT / "TREE.md", render_tree())
    write(ROOT / "INDEX.md", render_index())
    write(PROVENANCE / "ALIASES.tsv", render_aliases())


if __name__ == "__main__":
    main()
